import pandas as pd
from sqlalchemy import text

# ============================================================
# SECTION 1: EVENTS — CRUD for Event Management
# ============================================================

def get_all_events(session):
    """Fetch list of events including venue, organizer, categories, capacity, and current registrations."""
    query = text("""
        SELECT e.event_id, e.event_name, e.event_date, v.venue_name, o.organizer_name, e.status, e.base_price,
               GROUP_CONCAT(c.category_name SEPARATOR ', ') as categories,
               v.capacity,
               COALESCE(r_count.cnt, 0) as current_registrations
        FROM events e
        JOIN venues v ON e.venue_id = v.venue_id
        LEFT JOIN organizers o ON e.organizer_id = o.organizer_id
        LEFT JOIN (SELECT event_id, COUNT(*) as cnt FROM registrations GROUP BY event_id) r_count ON e.event_id = r_count.event_id
        LEFT JOIN event_categories ec ON e.event_id = ec.event_id
        LEFT JOIN categories c ON ec.category_id = c.category_id
        GROUP BY e.event_id, e.event_name, e.event_date, v.venue_name, o.organizer_name, e.status, e.base_price, v.capacity, r_count.cnt
        ORDER BY e.event_date DESC
    """)
    with session.get_bind().connect() as conn:
        df = pd.read_sql(query, conn)
    return df

def get_guest_registered_events(session, guest_id):
    """Fetch list of events that a specific guest HAS REGISTERED for."""
    query = text("""
        SELECT e.event_id, e.event_name, e.event_date, v.venue_name, o.organizer_name, e.status, e.base_price,
               GROUP_CONCAT(c.category_name SEPARATOR ', ') as categories
        FROM events e
        JOIN registrations r ON e.event_id = r.event_id
        JOIN venues v ON e.venue_id = v.venue_id
        LEFT JOIN organizers o ON e.organizer_id = o.organizer_id
        LEFT JOIN event_categories ec ON e.event_id = ec.event_id
        LEFT JOIN categories c ON ec.category_id = c.category_id
        WHERE r.guest_id = :gid
        GROUP BY e.event_id, e.event_name, e.event_date, v.venue_name, o.organizer_name, e.status, e.base_price
        ORDER BY e.event_date DESC
    """)
    with session.get_bind().connect() as conn:
        df = pd.read_sql(query, conn, params={"gid": guest_id})
    return df

def get_categories(session):
    """Fetch list of categories for dropdowns."""
    query = text("SELECT category_id, category_name FROM categories ORDER BY category_name ASC")
    with session.get_bind().connect() as conn:
        df = pd.read_sql(query, conn)
    return df

def create_event(session, name, start_datetime, end_datetime, venue_id, org_id, category_ids, price):
    """Insert a new event into the database."""
    query = text("""
        INSERT INTO events (event_name, event_date, end_time, venue_id, organizer_id, base_price)
        VALUES (:name, :start, :end, :v_id, :o_id, :price)
    """)
    try:
        session.execute(query, {
            "name": name, "start": start_datetime, "end": end_datetime,
            "v_id": venue_id, "o_id": org_id, "price": price
        })
        # Retrieve the ID of the newly created event
        result = session.execute(text("SELECT LAST_INSERT_ID()")).fetchone()
        new_event_id = result[0]
        
        # Insert event categories
        if category_ids:
            cat_query = text("INSERT INTO event_categories (event_id, category_id) VALUES (:eid, :cid)")
            for cid in category_ids:
                session.execute(cat_query, {"eid": new_event_id, "cid": cid})
                
        session.commit()
        return True, "Event created successfully!"
    except Exception as e:
        # Expected to trigger check_venue_conflict here if overlapping schedules exist
        session.rollback()
        error_msg = str(e)
        # Extract custom error message generated by MySQL signal
        if ']' in error_msg:
            parts = error_msg.split(']', 1)
            error_msg = parts[1].strip() if len(parts) > 1 else error_msg
        return False, f"Error: {error_msg}"

def get_event_by_id(session, event_id):
    """Fetch detailed information of a specific event by ID."""
    query = text("""
        SELECT event_id, event_name, event_date, end_time, venue_id, organizer_id, status, base_price
        FROM events
        WHERE event_id = :eid
    """)
    cat_query = text("SELECT category_id FROM event_categories WHERE event_id = :eid")
    
    with session.get_bind().connect() as conn:
        df = pd.read_sql(query, conn, params={"eid": event_id})
        cats_df = pd.read_sql(cat_query, conn, params={"eid": event_id})
        
    if not df.empty:
        df['category_ids'] = [cats_df['category_id'].tolist()]
    return df

def update_event(session, event_id, name, start_datetime, end_datetime, venue_id, org_id, category_ids, price):
    """Update event information."""
    query = text("""
        UPDATE events
        SET event_name = :name, event_date = :start, end_time = :end,
            venue_id = :v_id, organizer_id = :o_id, base_price = :price
        WHERE event_id = :eid
    """)
    try:
        session.execute(query, {
            "name": name, "start": start_datetime, "end": end_datetime,
            "v_id": venue_id, "o_id": org_id, "price": price,
            "eid": event_id
        })
        
        # Delete old category mappings and insert new ones
        session.execute(text("DELETE FROM event_categories WHERE event_id = :eid"), {"eid": event_id})
        if category_ids:
            cat_query = text("INSERT INTO event_categories (event_id, category_id) VALUES (:eid, :cid)")
            for cid in category_ids:
                session.execute(cat_query, {"eid": event_id, "cid": cid})
                
        session.commit()
        return True, "Event updated successfully!"
    except Exception as e:
        session.rollback()
        error_msg = str(e)
        if ']' in error_msg:
            parts = error_msg.split(']', 1)
            error_msg = parts[1].strip() if len(parts) > 1 else error_msg
        return False, f"Error: {error_msg}"

# ============================================================
# SECTION 2: ATTENDANCE — CRUD for Registration & Check-in
# ============================================================

def get_events_list(session):
    """Return a list of (event_id, event_name) for dropdown selections."""
    query = text("""
        SELECT event_id, event_name FROM events ORDER BY event_date DESC
    """)
    with session.get_bind().connect() as conn:
        df = pd.read_sql(query, conn)
    return df

def get_available_events_for_guest(session, guest_id):
    """Return a list of events that a specific guest HAS NOT REGISTERED for yet."""
    query = text("""
        SELECT e.event_id, e.event_name, v.capacity, COALESCE(r_count.cnt, 0) as current_registrations
        FROM events e
        JOIN venues v ON e.venue_id = v.venue_id
        LEFT JOIN (SELECT event_id, COUNT(*) as cnt FROM registrations GROUP BY event_id) r_count ON e.event_id = r_count.event_id
        WHERE e.event_id NOT IN (
            SELECT event_id FROM registrations WHERE guest_id = :gid
        )
        ORDER BY e.event_date DESC
    """)
    with session.get_bind().connect() as conn:
        df = pd.read_sql(query, conn, params={"gid": guest_id})
    return df

def get_guests_list(session):
    """Return a list of (guest_id, guest_name) for dropdown selections."""
    query = text("""
        SELECT guest_id, guest_name FROM guests ORDER BY guest_name ASC
    """)
    with session.get_bind().connect() as conn:
        df = pd.read_sql(query, conn)
    return df

def get_registrations_by_event(session, event_id):
    """Fetch registration list for a specific event, JOINed with guests to show names."""
    query = text("""
        SELECT r.registration_id, g.guest_name, g.guest_email, g.phone_number,
               r.registration_date, r.attendance_status, r.feedback_rating
        FROM registrations r
        JOIN guests g ON r.guest_id = g.guest_id
        WHERE r.event_id = :eid
        ORDER BY r.registration_date DESC
    """)
    with session.get_bind().connect() as conn:
        df = pd.read_sql(query, conn, params={"eid": event_id})
    return df

def get_guest_own_registrations(session, event_id, guest_id):
    """Fetch the registration record of a specific guest for a specific event."""
    query = text("""
        SELECT r.registration_id, g.guest_name, g.guest_email, g.phone_number,
               r.registration_date, r.attendance_status, r.feedback_rating
        FROM registrations r
        JOIN guests g ON r.guest_id = g.guest_id
        WHERE r.event_id = :eid AND r.guest_id = :gid
        ORDER BY r.registration_date DESC
    """)
    with session.get_bind().connect() as conn:
        df = pd.read_sql(query, conn, params={"eid": event_id, "gid": guest_id})
    return df

def create_registration(session, event_id, guest_id):
    """Register a guest for an event. Check for duplicates and capacity before inserting."""
    # Check if already registered
    check_query = text("""
        SELECT COUNT(*) as cnt FROM registrations
        WHERE event_id = :eid AND guest_id = :gid
    """)
    result = session.execute(check_query, {"eid": event_id, "gid": guest_id}).fetchone()
    if result[0] > 0:
        return False, "This guest has already registered for this event!"

    # Check capacity
    capacity_query = text("""
        SELECT v.capacity, (SELECT COUNT(*) FROM registrations r WHERE r.event_id = :eid) as current_registrations
        FROM events e
        JOIN venues v ON e.venue_id = v.venue_id
        WHERE e.event_id = :eid
    """)
    capacity_result = session.execute(capacity_query, {"eid": event_id}).fetchone()
    if capacity_result:
        venue_capacity = capacity_result[0]
        current_registrations = capacity_result[1]
        if current_registrations >= venue_capacity:
            return False, "This event has reached its maximum capacity and is sold out!"

    # Insert new registration
    insert_query = text("""
        INSERT INTO registrations (event_id, guest_id, registration_date, attendance_status, feedback_rating)
        VALUES (:eid, :gid, NOW(), 0, 0)
    """)
    try:
        session.execute(insert_query, {"eid": event_id, "gid": guest_id})
        session.commit()
        return True, "Registration successful!"
    except Exception as e:
        session.rollback()
        return False, f"Error: {str(e)}"

def check_in_guest(session, registration_id):
    """Invoke Stored Procedure sp_check_in_guest to check-in a guest."""
    try:
        session.execute(text("CALL sp_check_in_guest(:rid)"), {"rid": registration_id})
        session.commit()
        return True, "Check-in successful!"
    except Exception as e:
        session.rollback()
        error_msg = str(e)
        # Extract message from SIGNAL SQLSTATE '45000'
        if ']' in error_msg:
            parts = error_msg.split(']', 1)
            error_msg = parts[1].strip() if len(parts) > 1 else error_msg
        return False, f"{error_msg}"

def get_attendance_summary(session):
    """Fetch attendance rate statistics from View vw_event_attendance_summary."""
    query = text("""
        SELECT * FROM vw_event_attendance_summary
    """)
    with session.get_bind().connect() as conn:
        df = pd.read_sql(query, conn)
    return df

def get_guest_profile(session, guest_id):
    """Fetch guest profile information by ID."""
    query = text("""
        SELECT guest_name, guest_email, phone_number
        FROM guests
        WHERE guest_id = :gid
    """)
    result = session.execute(query, {"gid": guest_id}).fetchone()
    if result:
        return {
            "name": result[0],
            "email": result[1],
            "phone": result[2]
        }
    return None

# ============================================================
# SECTION 3: FINANCE — CRUD for Finance Management
# ============================================================

def get_finance_summary(session):
    """Fetch financial summary from View vw_finance_summary."""
    query = text("""
        SELECT * FROM vw_finance_summary
    """)
    with session.get_bind().connect() as conn:
        df = pd.read_sql(query, conn)
    return df

def get_finance_by_event(session, event_id):
    """Fetch specific financial details for a single event."""
    query = text("""
        SELECT finance_id, planned_budget, actual_cost
        FROM event_finance
        WHERE event_id = :eid
    """)
    result = session.execute(query, {"eid": event_id}).fetchone()
    if result:
        return {
            "finance_id": result[0],
            "planned_budget": float(result[1]),
            "actual_cost": float(result[2])
        }
    return None

def update_finance(session, finance_id, planned_budget, actual_cost):
    """Update event financial records."""
    query = text("""
        UPDATE event_finance
        SET planned_budget = :pb, actual_cost = :ac
        WHERE finance_id = :fid
    """)
    try:
        session.execute(query, {
            "pb": planned_budget, "ac": actual_cost,
            "fid": finance_id
        })
        session.commit()
        return True, "Financial records updated successfully!"
    except Exception as e:
        session.rollback()
        return False, f"Error: {str(e)}"

# ============================================================
# SECTION 4: RECOMMENDATION — Fetching ML Dataset
# ============================================================

def get_data_for_recommendation(session):
    """
    Fetch training data for XGBoost from registration history.
    Includes event_id, guest_id, categories, base_price, and attendance_status (Target variable).
    """
    query = text("""
        SELECT 
            r.guest_id,
            e.event_id,
            e.base_price,
            r.attendance_status,
            GROUP_CONCAT(c.category_name SEPARATOR ', ') as categories
        FROM registrations r
        JOIN events e ON r.event_id = e.event_id
        LEFT JOIN event_categories ec ON e.event_id = ec.event_id
        LEFT JOIN categories c ON ec.category_id = c.category_id
        GROUP BY r.guest_id, e.event_id, e.base_price, r.attendance_status
    """)
    with session.get_bind().connect() as conn:
        df = pd.read_sql(query, conn)
    return df